"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ActivitySystem = exports.FinanceSystem = exports.EnergySystem = exports.PlayerSystem = exports.ClockSystem = void 0;
var clockSystem_1 = require("./clockSystem");
Object.defineProperty(exports, "ClockSystem", { enumerable: true, get: function () { return clockSystem_1.ClockSystem; } });
var playerSystem_1 = require("./playerSystem");
Object.defineProperty(exports, "PlayerSystem", { enumerable: true, get: function () { return playerSystem_1.PlayerSystem; } });
var energySystem_1 = require("./energySystem");
Object.defineProperty(exports, "EnergySystem", { enumerable: true, get: function () { return energySystem_1.EnergySystem; } });
var financeSystem_1 = require("./financeSystem");
Object.defineProperty(exports, "FinanceSystem", { enumerable: true, get: function () { return financeSystem_1.FinanceSystem; } });
var activitySystem_1 = require("./activitySystem");
Object.defineProperty(exports, "ActivitySystem", { enumerable: true, get: function () { return activitySystem_1.ActivitySystem; } });
